name: Ruby
on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
      issues: read
      repository-projects: read
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          persist-credentials: false
      - name: Set up Ruby 2.6
        uses: ruby/setup-ruby@89f90524b88a01fe6e0b732220432cc6142926af
        with:
          ruby-version: 2.6.10
          bundler-cache: true
      - name: Checks
        run: bundle exec awesome_bot --allow-redirect --request-delay 1 README.md
