name: Ruby
on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
      issues: read
      repository-projects: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false
      - name: Set up Ruby 2.6
        uses: ruby/setup-ruby@d45b1a4e94b71acab930e56e79c6aa188764e7f9
        with:
          ruby-version: 2.6.10
          bundler-cache: true
      - name: Checks
        run: bundle exec awesome_bot --allow-redirect --request-delay 1 README.md
